name: PServer
author: 0utplay
version: 1.0
main: de.tentact.privateserver.PrivateServer
api-version: 1.13
depend: [LanguageAPI, CloudNet-Bridge, ProtocolLib]
commands:
  privateserver:
    aliases: [pserver, ps, os, cs]
